/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWafEventsRouteImport } from './routes/_app.waf-events'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTopTriggersRouteImport } from './routes/_app.top-triggers'
import { Route as AppTokensRouteImport } from './routes/_app.tokens'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppRateLimitsRouteImport } from './routes/_app.rate-limits'
import { Route as AppGeoRouteImport } from './routes/_app.geo'
import { Route as AppExclusionsRouteImport } from './routes/_app.exclusions'
import { Route as AppBlocklistRouteImport } from './routes/_app.blocklist'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppServicesIndexRouteImport } from './routes/_app.services.index'
import { Route as AppServicesIdRouteImport } from './routes/_app.services.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWafEventsRoute = AppWafEventsRouteImport.update({
  id: '/waf-events',
  path: '/waf-events',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTopTriggersRoute = AppTopTriggersRouteImport.update({
  id: '/top-triggers',
  path: '/top-triggers',
  getParentRoute: () => AppRoute,
} as any)
const AppTokensRoute = AppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppRateLimitsRoute = AppRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoRoute = AppGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AppRoute,
} as any)
const AppExclusionsRoute = AppExclusionsRouteImport.update({
  id: '/exclusions',
  path: '/exclusions',
  getParentRoute: () => AppRoute,
} as any)
const AppBlocklistRoute = AppBlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServicesRoute,
} as any)
const AppServicesIdRoute = AppServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/audit': typeof AppAuditRoute
  '/blocklist': typeof AppBlocklistRoute
  '/exclusions': typeof AppExclusionsRoute
  '/geo': typeof AppGeoRoute
  '/rate-limits': typeof AppRateLimitsRoute
  '/services': typeof AppServicesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/top-triggers': typeof AppTopTriggersRoute
  '/users': typeof AppUsersRoute
  '/waf-events': typeof AppWafEventsRoute
  '/services/$id': typeof AppServicesIdRoute
  '/services/': typeof AppServicesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/audit': typeof AppAuditRoute
  '/blocklist': typeof AppBlocklistRoute
  '/exclusions': typeof AppExclusionsRoute
  '/geo': typeof AppGeoRoute
  '/rate-limits': typeof AppRateLimitsRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/top-triggers': typeof AppTopTriggersRoute
  '/users': typeof AppUsersRoute
  '/waf-events': typeof AppWafEventsRoute
  '/': typeof AppIndexRoute
  '/services/$id': typeof AppServicesIdRoute
  '/services': typeof AppServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/blocklist': typeof AppBlocklistRoute
  '/_app/exclusions': typeof AppExclusionsRoute
  '/_app/geo': typeof AppGeoRoute
  '/_app/rate-limits': typeof AppRateLimitsRoute
  '/_app/services': typeof AppServicesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tokens': typeof AppTokensRoute
  '/_app/top-triggers': typeof AppTopTriggersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/waf-events': typeof AppWafEventsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/services/$id': typeof AppServicesIdRoute
  '/_app/services/': typeof AppServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/audit'
    | '/blocklist'
    | '/exclusions'
    | '/geo'
    | '/rate-limits'
    | '/services'
    | '/settings'
    | '/tokens'
    | '/top-triggers'
    | '/users'
    | '/waf-events'
    | '/services/$id'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/audit'
    | '/blocklist'
    | '/exclusions'
    | '/geo'
    | '/rate-limits'
    | '/settings'
    | '/tokens'
    | '/top-triggers'
    | '/users'
    | '/waf-events'
    | '/'
    | '/services/$id'
    | '/services'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/audit'
    | '/_app/blocklist'
    | '/_app/exclusions'
    | '/_app/geo'
    | '/_app/rate-limits'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/tokens'
    | '/_app/top-triggers'
    | '/_app/users'
    | '/_app/waf-events'
    | '/_app/'
    | '/_app/services/$id'
    | '/_app/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waf-events': {
      id: '/_app/waf-events'
      path: '/waf-events'
      fullPath: '/waf-events'
      preLoaderRoute: typeof AppWafEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top-triggers': {
      id: '/_app/top-triggers'
      path: '/top-triggers'
      fullPath: '/top-triggers'
      preLoaderRoute: typeof AppTopTriggersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tokens': {
      id: '/_app/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AppTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rate-limits': {
      id: '/_app/rate-limits'
      path: '/rate-limits'
      fullPath: '/rate-limits'
      preLoaderRoute: typeof AppRateLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo': {
      id: '/_app/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof AppGeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exclusions': {
      id: '/_app/exclusions'
      path: '/exclusions'
      fullPath: '/exclusions'
      preLoaderRoute: typeof AppExclusionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blocklist': {
      id: '/_app/blocklist'
      path: '/blocklist'
      fullPath: '/blocklist'
      preLoaderRoute: typeof AppBlocklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppServicesRoute
    }
    '/_app/services/$id': {
      id: '/_app/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AppServicesIdRouteImport
      parentRoute: typeof AppServicesRoute
    }
  }
}

interface AppServicesRouteChildren {
  AppServicesIdRoute: typeof AppServicesIdRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
}

const AppServicesRouteChildren: AppServicesRouteChildren = {
  AppServicesIdRoute: AppServicesIdRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
}

const AppServicesRouteWithChildren = AppServicesRoute._addFileChildren(
  AppServicesRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBlocklistRoute: typeof AppBlocklistRoute
  AppExclusionsRoute: typeof AppExclusionsRoute
  AppGeoRoute: typeof AppGeoRoute
  AppRateLimitsRoute: typeof AppRateLimitsRoute
  AppServicesRoute: typeof AppServicesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTokensRoute: typeof AppTokensRoute
  AppTopTriggersRoute: typeof AppTopTriggersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWafEventsRoute: typeof AppWafEventsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBlocklistRoute: AppBlocklistRoute,
  AppExclusionsRoute: AppExclusionsRoute,
  AppGeoRoute: AppGeoRoute,
  AppRateLimitsRoute: AppRateLimitsRoute,
  AppServicesRoute: AppServicesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTokensRoute: AppTokensRoute,
  AppTopTriggersRoute: AppTopTriggersRoute,
  AppUsersRoute: AppUsersRoute,
  AppWafEventsRoute: AppWafEventsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
