package store

import (
	"context"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"

	"github.com/bhagyajitjagdev/ward/backend/internal/model"
)

type wafExclusionRow struct {
	bun.BaseModel `bun:"table:waf_exclusions,alias:wx"`

	ID        string    `bun:"id,pk"`
	Scope     string    `bun:"scope,notnull"`
	ServiceID *string   `bun:"service_id"`
	RuleID    int       `bun:"rule_id"`
	Path      string    `bun:"path"`
	PathMatch string    `bun:"path_match,notnull"`
	Methods   string    `bun:"methods,notnull"` // comma-joined uppercase list ('' = any)
	Target    string    `bun:"target"`
	SecLang   string    `bun:"seclang,notnull"`
	State     string    `bun:"state,notnull"`
	Source    string    `bun:"source,notnull"`
	CreatedAt time.Time `bun:"created_at,notnull"`
}

func splitMethods(s string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(s, ",")
}

func (r wafExclusionRow) toModel() model.WAFExclusion {
	return model.WAFExclusion{
		ID: r.ID, Scope: r.Scope, ServiceID: r.ServiceID, RuleID: r.RuleID,
		Path: r.Path, PathMatch: r.PathMatch, Methods: splitMethods(r.Methods),
		Target: r.Target, SecLang: r.SecLang, State: r.State,
		Source: r.Source, CreatedAt: r.CreatedAt,
	}
}

// CreateExclusion inserts an exclusion (server-assigned id + timestamp). SecLang
// is expected to be pre-generated by the caller.
func (s *Store) CreateExclusion(ctx context.Context, in model.WAFExclusion) (model.WAFExclusion, error) {
	id, err := uuid.NewV7()
	if err != nil {
		return model.WAFExclusion{}, err
	}
	row := wafExclusionRow{
		ID: id.String(), Scope: orDefault(in.Scope, "service"), ServiceID: in.ServiceID,
		RuleID: in.RuleID, Path: in.Path, PathMatch: orDefault(in.PathMatch, "prefix"),
		Methods: strings.Join(in.Methods, ","), Target: in.Target, SecLang: in.SecLang,
		State: orDefault(in.State, "active"), Source: orDefault(in.Source, "manual"),
		CreatedAt: time.Now().UTC(),
	}
	if _, err := s.DB.NewInsert().Model(&row).Exec(ctx); err != nil {
		return model.WAFExclusion{}, err
	}
	return row.toModel(), nil
}

// ListExclusions returns all exclusions, newest first.
func (s *Store) ListExclusions(ctx context.Context) ([]model.WAFExclusion, error) {
	var rows []wafExclusionRow
	if err := s.DB.NewSelect().Model(&rows).Order("created_at DESC").Scan(ctx); err != nil {
		return nil, err
	}
	out := make([]model.WAFExclusion, 0, len(rows))
	for _, r := range rows {
		out = append(out, r.toModel())
	}
	return out, nil
}

// DeleteExclusion removes an exclusion; reports whether one was found.
func (s *Store) DeleteExclusion(ctx context.Context, id string) (bool, error) {
	res, err := s.DB.NewDelete().Model((*wafExclusionRow)(nil)).Where("id = ?", id).Exec(ctx)
	if err != nil {
		return false, err
	}
	n, _ := res.RowsAffected()
	return n > 0, nil
}
