/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + DB reachability */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Running Ward build version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This specification (JSON) */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether first-run setup is still needed */
        get: operations["authState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the owner account (first run only) */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create a user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user (not the owner) */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List machine API tokens */
        get: operations["listApiTokens"];
        put?: never;
        /** Create a token (secret returned once) */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a token */
        delete: operations["revokeApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit trail, newest first */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard aggregates (24h) */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List services */
        get: operations["listServices"];
        put?: never;
        /** Create a service (reconciles the edge) */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a service */
        get: operations["getService"];
        put?: never;
        post?: never;
        /** Delete a service (reconciles the edge) */
        delete: operations["deleteService"];
        options?: never;
        head?: never;
        /** Update a service (full object; reconciles the edge) */
        patch: operations["updateService"];
        trace?: never;
    };
    "/waf-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WAF detections, newest first */
        get: operations["listWafEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waf-events/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detections clustered by (service, path, rule, target) */
        get: operations["topTriggers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access log, newest first */
        get: operations["listAccessEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-events/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access-log aggregates */
        get: operations["accessStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waf-exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List WAF exclusions */
        get: operations["listExclusions"];
        put?: never;
        /** Create a scoped exclusion (SecLang generated server-side) */
        post: operations["createExclusion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waf-exclusions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an exclusion (reconciles the edge) */
        delete: operations["deleteExclusion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waf-custom-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user-authored raw SecLang rules */
        get: operations["listWafCustomRules"];
        put?: never;
        /** Create a raw SecLang rule (validated against the edge before it's kept) */
        post: operations["createWafCustomRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waf-custom-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a rule (reconciles the edge) */
        delete: operations["deleteWafCustomRule"];
        options?: never;
        head?: never;
        /** Update a rule (validated against the edge; reverted on rejection) */
        patch: operations["updateWafCustomRule"];
        trace?: never;
    };
    "/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List IP block/allow rules */
        get: operations["listBlocklist"];
        put?: never;
        /** Create a rule (reconciles the edge) */
        post: operations["createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocklist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a rule (reconciles the edge) */
        delete: operations["deleteBlock"];
        options?: never;
        head?: never;
        /** Update a rule (reconciles the edge) */
        patch: operations["updateBlock"];
        trace?: never;
    };
    "/rate-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rate limits */
        get: operations["listRateLimits"];
        put?: never;
        /** Create a rate limit (reconciles the edge) */
        post: operations["createRateLimit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rate-limits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a rate limit (reconciles the edge) */
        delete: operations["deleteRateLimit"];
        options?: never;
        head?: never;
        /** Update a rate limit (reconciles the edge) */
        patch: operations["updateRateLimit"];
        trace?: never;
    };
    "/geo-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List geo rules */
        get: operations["listGeoRules"];
        put?: never;
        /** Create a geo rule (reconciles the edge) */
        post: operations["createGeoRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a geo rule (reconciles the edge) */
        delete: operations["deleteGeoRule"];
        options?: never;
        head?: never;
        /** Update a geo rule (reconciles the edge) */
        patch: operations["updateGeoRule"];
        trace?: never;
    };
    "/geoip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GeoIP database status */
        get: operations["geoipStatus"];
        put?: never;
        post?: never;
        /** Remove the GeoIP database */
        delete: operations["geoipDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geoip/dbip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download the free DB-IP country database */
        post: operations["geoipDBIP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geoip/maxmind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download GeoLite2 with a MaxMind license key */
        post: operations["geoipMaxMind"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geoip/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an .mmdb file */
        post: operations["geoipUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Applied-config snapshots, newest first (without config bodies) */
        get: operations["listSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config-snapshots/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push a snapshot's config back to the edge */
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edge-wide settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update whichever settings are present (audited; reconciles) */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/crowdsec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CrowdSec status + active decisions (read-only; the bouncer enforces them) */
        get: operations["crowdsecStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded custom certificates */
        get: operations["listCertificates"];
        put?: never;
        /** Upload a PEM cert + key (name auto-derived when omitted) */
        post: operations["uploadCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an uploaded certificate */
        delete: operations["deleteCertificate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Health: {
            status: string;
        };
        VersionInfo: {
            version: string;
        };
        AuthState: {
            needs_setup: boolean;
        };
        Credentials: {
            username: string;
            password: string;
        };
        User: {
            id: string;
            username: string;
            role: string;
            is_owner: boolean;
            /** Format: date-time */
            created_at: string;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        WafMode: "DetectionOnly" | "On";
        /**
         * @description Per-service override — "" inherits the global default.
         * @enum {string}
         */
        ServiceWafMode: "" | "DetectionOnly" | "On";
        Service: {
            id: string;
            name: string;
            /** @description Primary hostname (first of public_hostnames); read-only alias. */
            public_hostname: string;
            /** @description Every hostname this service answers on — one route, one policy. */
            public_hostnames: string[];
            upstreams: string[];
            lb_policy: string;
            tls_mode: string;
            waf_enabled: boolean;
            waf_mode: components["schemas"]["ServiceWafMode"];
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ServiceInput: {
            name: string;
            /** @description Optional single-hostname shorthand; public_hostnames wins if both are sent. */
            public_hostname?: string;
            /** @description One or more hostnames; the first is the primary. */
            public_hostnames: string[];
            upstreams: string[];
            lb_policy?: string;
            tls_mode?: string;
            waf_enabled?: boolean;
            waf_mode?: components["schemas"]["ServiceWafMode"];
        };
        ServiceUpdate: components["schemas"]["ServiceInput"] & {
            enabled: boolean;
        };
        Settings: {
            waf_engine_mode: components["schemas"]["WafMode"];
            acme_email: string;
            access_retention_days: number;
            waf_retention_days: number;
            /** @description Read-only — OWASP CRS version the running edge reported. */
            crs_version?: string;
            /** @description Whether the CrowdSec bouncer is wired into the edge. */
            crowdsec_enabled?: boolean;
            /** @description Read-only — LAPI URL + key are set in the deployment. */
            crowdsec_configured?: boolean;
        };
        /** @description Only the fields present (non-zero) are applied. */
        SettingsUpdate: {
            waf_engine_mode?: components["schemas"]["WafMode"];
            acme_email?: string;
            access_retention_days?: number;
            waf_retention_days?: number;
            crowdsec_enabled?: boolean;
        };
        CrowdSecStatus: {
            /** @description LAPI URL + key present. */
            configured: boolean;
            /** @description Bouncer wired into the edge. */
            enabled: boolean;
            /** @description LAPI answered. */
            reachable: boolean;
            error?: string;
            decisions: components["schemas"]["CrowdSecDecision"][];
        };
        CrowdSecDecision: {
            id?: number;
            origin?: string;
            /** @description ban | captcha | throttle */
            type?: string;
            /** @description Ip | Range | ... */
            scope?: string;
            /** @description The banned IP/CIDR. */
            value: string;
            duration?: string;
            scenario?: string;
        };
        Certificate: {
            /** @description Storage name (label) — coverage comes from `subjects`. */
            domain: string;
            subjects: string[];
            /** Format: date-time */
            not_after: string;
            /** Format: date-time */
            updated_at: string;
        };
        CertificateInput: {
            /** @description Optional label; auto-derived from the cert when empty. */
            domain?: string;
            cert_pem: string;
            key_pem: string;
        };
        WafEvent: {
            id: string;
            tx_id: string;
            /** Format: date-time */
            ts: string;
            service_id?: string | null;
            host: string;
            client_ip: string;
            authed: boolean;
            user_agent?: string;
            method: string;
            path: string;
            uri: string;
            status: number;
            engine_mode: string;
            is_interrupted: boolean;
            rule_id: number;
            rule_msg: string;
            severity: string;
            matched_target?: string;
            matched_value?: string;
            tags: string[];
            is_anomaly_score: boolean;
            crs_version?: string;
            raw?: string;
        };
        WafTrigger: {
            service_id?: string | null;
            host?: string;
            path: string;
            rule_id: number;
            rule_msg: string;
            severity: string;
            matched_target?: string;
            hits: number;
            distinct_ips: number;
            /** Format: date-time */
            first_seen: string;
            /** Format: date-time */
            last_seen: string;
        };
        /** @enum {string} */
        Scope: "global" | "service";
        /** @enum {string} */
        BlockMode: "block" | "allow";
        /**
         * @description How `path` is matched against the request URI. Default prefix.
         * @enum {string}
         */
        PathMatch: "exact" | "prefix" | "regex";
        WafExclusion: {
            id: string;
            scope: components["schemas"]["Scope"];
            service_id?: string | null;
            rule_id: number;
            path?: string;
            path_match?: components["schemas"]["PathMatch"];
            /** @description Restrict to these HTTP methods; empty = any. */
            methods?: string[];
            target?: string;
            seclang: string;
            state: string;
            source: string;
            /** Format: date-time */
            created_at: string;
        };
        ExclusionInput: {
            rule_id: number;
            scope: components["schemas"]["Scope"];
            service_id?: string | null;
            path?: string;
            path_match?: components["schemas"]["PathMatch"];
            methods?: string[];
            target?: string;
        };
        WafCustomRule: {
            id: string;
            scope: components["schemas"]["Scope"];
            service_id?: string | null;
            name: string;
            seclang: string;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WafCustomRuleInput: {
            scope?: components["schemas"]["Scope"];
            service_id?: string | null;
            name: string;
            /** @description Raw SecLang (multi-line). Injected before the CRS include, after Ward's generated exclusions. */
            seclang: string;
            enabled?: boolean;
        };
        Block: {
            id: string;
            scope: components["schemas"]["Scope"];
            mode: components["schemas"]["BlockMode"];
            service_id?: string | null;
            cidr: string;
            reason?: string;
            source: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        BlockInput: {
            cidr: string;
            scope?: components["schemas"]["Scope"];
            mode?: components["schemas"]["BlockMode"];
            service_id?: string | null;
            reason?: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        RateLimit: {
            id: string;
            scope: components["schemas"]["Scope"];
            service_id?: string | null;
            max_events: number;
            /** @description Go duration, e.g. 10s / 1m. */
            window: string;
            /** Format: date-time */
            created_at: string;
        };
        RateLimitInput: {
            scope: components["schemas"]["Scope"];
            service_id?: string | null;
            max_events: number;
            window: string;
        };
        GeoRule: {
            id: string;
            scope: components["schemas"]["Scope"];
            mode: components["schemas"]["BlockMode"];
            service_id?: string | null;
            countries: string[];
            /** Format: date-time */
            created_at: string;
        };
        GeoRuleInput: {
            scope: components["schemas"]["Scope"];
            mode?: components["schemas"]["BlockMode"];
            service_id?: string | null;
            countries: string[];
        };
        GeoIPStatus: {
            present: boolean;
            source?: string;
            filename?: string;
            /** Format: int64 */
            size?: number;
            /** Format: date-time */
            updated_at?: string;
            dir: string;
        };
        ApiToken: {
            id: string;
            name: string;
            user_id?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            revoked: boolean;
            /** Format: date-time */
            created_at: string;
            /** @description Present only in the creation response. */
            token?: string;
        };
        AuditEntry: {
            id: string;
            actor: string;
            action: string;
            target?: string;
            detail?: string;
            /** Format: date-time */
            created_at: string;
        };
        Overview: {
            services: number;
            waf_services: number;
            detections_24h: number;
            blocked_24h: number;
            requests_24h: number;
            active_blocks: number;
            activity: {
                /** Format: date-time */
                hour: string;
                detections: number;
                blocked: number;
                requests: number;
            }[];
            by_service: {
                service_id: string;
                detections_24h: number;
            }[];
        };
        AccessEvent: {
            id: string;
            /** Format: date-time */
            ts: string;
            service_id?: string | null;
            host: string;
            client_ip: string;
            method: string;
            path: string;
            query?: string;
            status: number;
            duration_ms: number;
            /** Format: int64 */
            bytes: number;
            user_agent?: string;
        };
        AccessStats: {
            /** Format: int64 */
            total: number;
            status: {
                /** Format: int64 */
                "2xx": number;
                /** Format: int64 */
                "3xx": number;
                /** Format: int64 */
                "4xx": number;
                /** Format: int64 */
                "5xx": number;
            };
            /** Format: int64 */
            bytes: number;
            avg_ms: number;
            p95_ms: number;
            series: {
                bucket: string;
                /** Format: int64 */
                requests: number;
                /** Format: int64 */
                errors: number;
            }[];
            top_paths: {
                path: string;
                count: number;
            }[];
        };
        ConfigSnapshot: {
            id: string;
            note?: string;
            active: boolean;
            /** Format: date-time */
            created_at: string;
            /** @description Present only when fetching a single snapshot. */
            caddy_json?: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        id: string;
    };
    requestBodies: {
        Credentials: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    authState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Credentials"];
        responses: {
            /** @description Owner created; session started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Credentials"];
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Credentials"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listApiTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiToken"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created — `token` present only in this response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiToken"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAuditLog: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWafEvents: {
        parameters: {
            query?: {
                service_id?: string;
                path?: string;
                client_ip?: string;
                rule_id?: number;
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafEvent"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    topTriggers: {
        parameters: {
            query?: {
                service_id?: string;
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafTrigger"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAccessEvents: {
        parameters: {
            query?: {
                service_id?: string;
                client_ip?: string;
                method?: string;
                path?: string;
                status?: number;
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessEvent"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    accessStats: {
        parameters: {
            query?: {
                service_id?: string;
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessStats"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExclusions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafExclusion"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createExclusion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExclusionInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafExclusion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteExclusion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listWafCustomRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafCustomRule"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createWafCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WafCustomRuleInput"];
            };
        };
        responses: {
            /** @description Created — the edge accepted the rule */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafCustomRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteWafCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateWafCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WafCustomRuleInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WafCustomRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listBlocklist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRateLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimit"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateLimitInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimit"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateLimitInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimit"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGeoRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoRule"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createGeoRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeoRuleInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteGeoRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateGeoRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeoRuleInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    geoipStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoIPStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    geoipDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    geoipDBIP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoIPStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    geoipMaxMind: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    license_key: string;
                };
            };
        };
        responses: {
            /** @description Downloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoIPStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    geoipUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoIPStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSnapshot"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rolled back */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        snapshot_id: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    crowdsecStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrowdSecStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCertificates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateInput"];
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
